### ISSUE TITLE
Lost node - no longer building

### ISSUE THREAD

**Issue by magick93** [aerogear/aerogear-digger-installer#120]
## Description

I have lost an Openshift node, and now the jenkins build hangs with:

```
[Pipeline] node
Still waiting to schedule task
Jenkins doesn’t have label android
```

## Expected Behavior

Builds, happily

## Actual Behavior

See above

## Questions

Do I need to label a new openshift node?
If yes, what should the label be?

Thanks

**Comment by odra** [comment]
Are there any relevant openshift logs in the "events" tab? This message usually shows up while jenkins is waiting for openshift to create the android builder pod.

**Comment by magick93** [comment]
Thanks.

I checked the jenkins logs, and just needed to build the android image again.
